apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: petal-take-home-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: petal-take-home  
    spec:                  
      containers: 
      - name: petal-take-home 
        image: petal-take-home:v1
        ports:
        - containerPort: 3000